---
galaxy_info:
  author: Jim Tarpley (@trippsc2)
  namespace: trippsc2
  role_name: windows
  description: This role seals a Windows machine for use as a template.

  license: MIT

  min_ansible_version: '2.16'

  platforms:
    - name: Windows
      versions:
        - all

collections:
  - ansible.windows
  - community.windows

dependencies: []
