---
galaxy_info:
  author: Jim Tarpley
  namespace: trippsc2
  role_name: win_seal_for_template
  description: This role seals a Windows machine for use as a template.

  license: MIT

  min_ansible_version: '2.15'

  platforms:
    - name: Windows
      versions:
        - '2019'
        - '2022'

collections:
  - ansible.windows
  - community.windows

dependencies: []
