---
galaxy_info:
  author: Jim Tarpley
  namespace: trippsc2
  role_name: ubuntu_seal_for_template
  description: This role seals an Ubuntu machine for use as a template.

  license: MIT

  min_ansible_version: '2.14'

  platforms:
    - name: Ubuntu
      versions:
        - focal
        - jammy
        - noble

dependencies: []
