---
galaxy_info:
  author: Jim Tarpley (@trippsc2)
  namespace: trippsc2
  role_name: ubuntu
  description: This role seals an Ubuntu machine for use as a template.

  license: MIT

  min_ansible_version: '2.16'

  platforms:
    - name: Ubuntu
      versions:
        - noble
        - jammy
        - focal

dependencies: []
