---
- name: Restart systemd-resolved
  listen: _debian_restart_systemd-resolved
  become: true
  ansible.builtin.systemd_service:
    name: systemd-resolved.service
    state: restarted

- name: Update SSL CA certificates
  listen: _debian_update_ca_trust
  become: true
  ansible.builtin.command: update-ca-certificates
  changed_when: true

- name: Regenerate SSH host keys
  listen: _debian_regenerate_ssh_host_keys
  become: true
  ansible.builtin.command: dpkg-reconfigure openssh-server
  changed_when: true
