---
galaxy_info:
  author: Jim Tarpley (@trippsc2)
  namespace: trippsc2
  role_name: bleachbit
  description: This role runs Bleachbit from a portable executable on Windows systems.
  license: MIT

  min_ansible_version: '2.15'

  platforms:
  - name: Windows
    versions:
      - '2019'
      - '2022'

collections:
  - ansible.windows
  - chocolatey.chocolatey

dependencies: []
