---
galaxy_info:
  author: Jim Tarpley (@trippsc2)
  namespace: trippsc2
  role_name: rhel
  description: This role seals a RHEL-based machine for use as a template.

  license: MIT

  min_ansible_version: '2.16'

  platforms:
    - name: EL
      versions:
        - '9'
        - '8'

dependencies: []
