---
galaxy_info:
  author: Jim Tarpley
  namespace: trippsc2
  role_name: rhel
  description: This role seals a RHEL-based machine for use as a template.

  license: MIT

  min_ansible_version: '2.14'

  platforms:
    - name: EL
      versions:
        - '8'
        - '9'

dependencies: []
